services:
  web:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: guestbook:latest
    # container_name: guestbook_web #optional as Docker Compose assigns a name
    ports:
      - "5000:5000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=myuser
      - DATABASE_PASSWORD=mypassword
      - DATABASE_NAME=guestbook_db
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    # container_name: guestbook_mysql_db #optional as Docker Compose assigns a name
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_DATABASE: guestbook_db
    volumes:
      - db_data:/var/lib/mysql
    # ports:
      # - "3306:3306"
    healthcheck:
      #NOT WORKING test: ["CMD", 'mysqladmin', 'ping', '-h', '127.0.0.1', '-u', 'root', '--password=$$MYSQL_ROOT_PASSWORD' ]
      test: ["CMD-SHELL", "mysql $$MYSQL_DATABASE -u $$MYSQL_USER -p$$MYSQL_PASSWORD -h 127.0.0.1 -e 'show tables;' 2>&1"]
      interval: 10s
      timeout: 5s
      retries: 5      

volumes:
  db_data: