version: "3.9"

services:
  web:
    image: guestbook:latest
    container_name: my-flask-guestbook
    working_dir: /app
    volumes:
      - ./app:/app
      - ./static:/app/static # per i file statici
    ports:
      - "5000:5000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=${DB_USER}
      - DATABASE_PASSWORD=${DB_PASSWORD}
      - DATABASE_NAME=guestbook_db
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: my_mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: guestbook_db
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data: